#!/usr/bin/env bash
# ============================================================
# install-openvpn.sh — راه‌اندازی کامل OpenVPN روی Ubuntu
# ============================================================
# این اسکریپت را با دسترسی root اجرا کنید:
#   sudo bash install-openvpn.sh
#
# متغیرهای محیطی قابل سفارشی‌سازی:
#   OPENVPN_PORT   (پیش‌فرض: 1194)
#   OPENVPN_PROTO  (پیش‌فرض: udp)
#   OPENVPN_SERVER_IP  (پیش‌فرض: auto-detect)
#   OPENVPN_DNS1   (پیش‌فرض: 1.1.1.1)
#   OPENVPN_DNS2   (پیش‌فرض: 8.8.8.8)
# ============================================================

set -euo pipefail

# ─── رنگ‌بندی خروجی ────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERR]${NC}  $*"; exit 1; }

# ─── بررسی root ────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "این اسکریپت باید با دسترسی root اجرا شود. از 'sudo bash install-openvpn.sh' استفاده کنید."

# ─── تنظیمات ───────────────────────────────────────────────
PORT="${OPENVPN_PORT:-1194}"
PROTO="${OPENVPN_PROTO:-udp}"
DNS1="${OPENVPN_DNS1:-1.1.1.1}"
DNS2="${OPENVPN_DNS2:-8.8.8.8}"

# تشخیص خودکار IP عمومی سرور
if [[ -z "${OPENVPN_SERVER_IP:-}" ]]; then
    SERVER_IP=$(curl -s --max-time 10 https://api.ipify.org 2>/dev/null || \
                curl -s --max-time 10 https://ifconfig.me 2>/dev/null || \
                hostname -I | awk '{print $1}')
else
    SERVER_IP="$OPENVPN_SERVER_IP"
fi

EASYRSA_DIR="/etc/openvpn/easy-rsa"
PKI_DIR="${EASYRSA_DIR}/pki"
SERVER_DIR="/etc/openvpn/server"
CLIENT_DIR="/etc/openvpn/client"
LOG_DIR="/var/log/openvpn"

# ─── شناسایی اینترفیس شبکه اصلی ──────────────────────────
NIC=$(ip route get 8.8.8.8 2>/dev/null | awk 'NR==1{for(i=1;i<=NF;i++) if($i=="dev") {print $(i+1); exit}}')
[[ -z "$NIC" ]] && NIC="eth0"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      نصب OpenVPN Server روی Ubuntu                   ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
info "IP سرور       : $SERVER_IP"
info "پورت           : $PORT/$PROTO"
info "DNS            : $DNS1, $DNS2"
info "اینترفیس شبکه  : $NIC"
echo ""

# ─── 1. به‌روزرسانی و نصب پکیج‌ها ──────────────────────────
info "در حال نصب OpenVPN و EasyRSA..."
apt-get update -qq
apt-get install -y -qq openvpn easy-rsa curl iptables-persistent
success "پکیج‌های مورد نیاز نصب شدند."

# ─── 2. راه‌اندازی EasyRSA PKI ─────────────────────────────
info "در حال راه‌اندازی PKI با EasyRSA..."

mkdir -p "$EASYRSA_DIR"
cp -r /usr/share/easy-rsa/* "$EASYRSA_DIR/"
cd "$EASYRSA_DIR"

# ایجاد فایل پیکربندی EasyRSA
cat > "$EASYRSA_DIR/vars" <<'EOF'
set_var EASYRSA_ALGO        ec
set_var EASYRSA_CURVE       prime256v1
set_var EASYRSA_DIGEST      sha256
set_var EASYRSA_CA_EXPIRE   3650
set_var EASYRSA_CERT_EXPIRE 825
set_var EASYRSA_BATCH        1
set_var EASYRSA_REQ_CN       "VPN-CA"
set_var EASYRSA_REQ_COUNTRY  "IR"
set_var EASYRSA_REQ_PROVINCE "Tehran"
set_var EASYRSA_REQ_CITY     "Tehran"
set_var EASYRSA_REQ_ORG      "VPN Service"
set_var EASYRSA_REQ_EMAIL    "admin@vpn.local"
EOF

# init PKI
./easyrsa init-pki

# ساخت CA
info "در حال ساخت CA..."
./easyrsa build-ca nopass

# ساخت گواهی سرور
info "در حال ساخت گواهی سرور..."
./easyrsa gen-req server nopass
./easyrsa sign-req server server

# ساخت پارامتر DH (با ECDH سریع‌تر است ولی برای سازگاری DH هم می‌سازیم)
info "در حال ساخت پارامترهای DH (ممکن است کمی طول بکشد)..."
openssl dhparam -out "$PKI_DIR/dh.pem" 2048 2>/dev/null
success "پارامترهای DH ساخته شدند."

# ساخت TLS Auth Key
info "در حال ساخت TLS Auth Key..."
mkdir -p "$SERVER_DIR"
openvpn --genkey secret "$SERVER_DIR/ta.key"

# کپی فایل‌های گواهی به پوشه سرور
info "در حال کپی فایل‌های گواهی..."
cp "$PKI_DIR/ca.crt"                    "$SERVER_DIR/"
cp "$PKI_DIR/issued/server.crt"         "$SERVER_DIR/"
cp "$PKI_DIR/private/server.key"        "$SERVER_DIR/"
cp "$PKI_DIR/dh.pem"                    "$SERVER_DIR/"

# تنظیم مجوزهای امن
chmod 600 "$SERVER_DIR/server.key" "$SERVER_DIR/ta.key"
chmod 644 "$SERVER_DIR/ca.crt" "$SERVER_DIR/server.crt" "$SERVER_DIR/dh.pem"

success "گواهی‌های OpenVPN ساخته شدند."

# ─── 3. ایجاد پیکربندی سرور ──────────────────────────────
info "در حال ایجاد فایل پیکربندی سرور..."

mkdir -p "$LOG_DIR"

cat > "/etc/openvpn/server/server.conf" <<EOF
# ============================================================
# OpenVPN Server Configuration
# Generated by install-openvpn.sh
# ============================================================

port ${PORT}
proto ${PROTO}
dev tun

# گواهی‌ها
ca    ${SERVER_DIR}/ca.crt
cert  ${SERVER_DIR}/server.crt
key   ${SERVER_DIR}/server.key
dh    ${SERVER_DIR}/dh.pem

# TLS Authentication (لایه امنیتی اضافه)
tls-auth ${SERVER_DIR}/ta.key 0
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384

# رمزنگاری
cipher AES-256-GCM
auth SHA256
ncp-ciphers AES-256-GCM:AES-128-GCM

# شبکه VPN: کاربران IP از محدوده 10.8.0.0/24 دریافت می‌کنند
server 10.8.0.0 255.255.255.0

# ارسال ترافیک از طریق VPN
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS ${DNS1}"
push "dhcp-option DNS ${DNS2}"

# نگه‌دسترسی زنده
keepalive 10 120

# کاربر و گروه (امنیت)
user nobody
group nogroup

# حفظ تنظیمات پس از restart
persist-key
persist-tun

# لاگ‌ها
status  ${LOG_DIR}/openvpn-status.log 30
log-append ${LOG_DIR}/openvpn.log
verb 3
mute 20

# جلوگیری از اثر fingerprinting
reneg-sec 0

# اجازه حداکثر یک اتصال همزمان برای هر کاربر
duplicate-cn

# فایل CRL برای ابطال گواهی‌ها
# (پس از revoke هر گواهی فعال می‌شود)
# crl-verify ${PKI_DIR}/crl.pem
EOF

# لینک دادن server.conf به پوشه اصلی openvpn
ln -sf "/etc/openvpn/server/server.conf" "/etc/openvpn/server.conf"

success "فایل پیکربندی سرور ایجاد شد."

# ─── 4. فعال کردن IP Forwarding ───────────────────────────
info "در حال فعال‌سازی IP Forwarding..."
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-openvpn.conf
sysctl -p /etc/sysctl.d/99-openvpn.conf -q
success "IP Forwarding فعال شد."

# ─── 5. تنظیم iptables / NAT ──────────────────────────────
info "در حال تنظیم iptables NAT..."

# حذف قوانین قبلی اگر وجود دارند
iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o "$NIC" -j MASQUERADE 2>/dev/null || true
iptables -D INPUT -p "$PROTO" --dport "$PORT" -j ACCEPT 2>/dev/null || true
iptables -D FORWARD -s 10.8.0.0/24 -j ACCEPT 2>/dev/null || true
iptables -D FORWARD -d 10.8.0.0/24 -j ACCEPT 2>/dev/null || true

# اضافه کردن قوانین جدید
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o "$NIC" -j MASQUERADE
iptables -I INPUT  -p "$PROTO" --dport "$PORT" -j ACCEPT
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -I FORWARD -d 10.8.0.0/24 -j ACCEPT

# ذخیره قوانین iptables
netfilter-persistent save 2>/dev/null || iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
success "قوانین iptables تنظیم شدند."

# ─── 6. فعال‌سازی و اجرای سرویس ──────────────────────────
info "در حال راه‌اندازی سرویس OpenVPN..."
systemctl enable openvpn-server@server 2>/dev/null || systemctl enable openvpn@server 2>/dev/null || true
systemctl restart openvpn-server@server 2>/dev/null || systemctl restart openvpn@server 2>/dev/null || true

sleep 2

if systemctl is-active --quiet openvpn-server@server 2>/dev/null || systemctl is-active --quiet openvpn@server 2>/dev/null; then
    success "سرویس OpenVPN با موفقیت راه‌اندازی شد."
else
    warn "سرویس OpenVPN راه‌اندازی نشد. لاگ را بررسی کنید: journalctl -u openvpn-server@server -n 50"
fi

# ─── 7. ذخیره اطلاعات کانفیگ ─────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cat > "${SCRIPT_DIR}/config/openvpn-install-info.json" <<EOF
{
  "server_ip":   "${SERVER_IP}",
  "port":        "${PORT}",
  "proto":       "${PROTO}",
  "pki_dir":     "${PKI_DIR}",
  "server_dir":  "${SERVER_DIR}",
  "ta_key":      "${SERVER_DIR}/ta.key",
  "ca_cert":     "${PKI_DIR}/ca.crt",
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

success "اطلاعات نصب در config/openvpn-install-info.json ذخیره شد."

# ─── خلاصه نهایی ──────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         ✅ نصب OpenVPN با موفقیت انجام شد!           ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}IP سرور:${NC}    $SERVER_IP"
echo -e "  ${CYAN}پورت:${NC}       $PORT/$PROTO"
echo -e "  ${CYAN}PKI:${NC}        $EASYRSA_DIR"
echo -e "  ${CYAN}گواهی‌ها:${NC}   $SERVER_DIR"
echo -e "  ${CYAN}لاگ:${NC}        $LOG_DIR"
echo ""
echo -e "  برای مدیریت کاربران از پنل ادمین استفاده کنید:"
echo -e "  ${CYAN}http://127.0.0.1:5000/openvpn${NC}"
echo ""
echo -e "  برای بررسی وضعیت سرویس:"
echo -e "  ${CYAN}systemctl status openvpn-server@server${NC}"
echo ""
